inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'vendor/**/*'
    - 'bin/*'
Metrics/AbcSize:
  Max: 40
Style/SpaceInsideBrackets:
  Enabled: false # spaces make enums in models more readable
Metrics/MethodLength:
  Max: 20

# disable for generated files
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/*'
    - 'test/test_helper.rb'